plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.10'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.oath'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    // Lombok을 JDK21과 호환성이 더 좋은 최신 안정 버전으로 업데이트
    lombokVersion = '1.18.32'
}

dependencies {

    //PostSQL + pgvector
    implementation "org.springframework.ai:spring-ai-pgvector-store:1.0.0"
    implementation 'org.postgresql:postgresql:42.7.4'

    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'

    // YML 설정을 자바 객체로 바인딩할 때 꼭 필요한 라이브러리
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Caffeine
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'com.github.ben-manes.caffeine:caffeine'

    // Webflux
    implementation 'org.springframework:spring-webflux'

    // QueryDSL
    implementation "com.querydsl:querydsl-jpa::jakarta"
    annotationProcessor "com.querydsl:querydsl-apt::jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    // JWT 토큰
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // 스프링
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // 머스테치
    implementation 'org.springframework.boot:spring-boot-starter-mustache'

    // Lombok (버전 고정)
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
