spring:
  # ===================================================================
  # 1. 데이터소스(DB) 설정
  # ===================================================================
  datasource:
    # url: jdbc:h2:mem:solidtask -> 'solidtask'라는 이름의 메모리 기반 DB를 사용합니다.
    url: jdbc:h2:mem:oath
    username: sa # H2 DB 기본 사용자 이름
    password: # 비밀번호는 없음
    driver-class-name: org.h2.Driver # H2 드라이버 지정

  # ===================================================================
  # 2. H2 데이터베이스 콘솔 설정
  # ===================================================================
  h2:
    console:
      enabled: true # H2 콘솔 기능 활성화
      path: /h2-console # <http://localhost:8080/h2-console>

  # ===================================================================
  # 3. JPA 및 Hibernate 설정
  # ===================================================================
  jpa:
    # Hibernate에 대한 설정
    hibernate:
      # ddl-auto: 애플리케이션 실행 시점에 DB 스키마(테이블 등)를 어떻게 처리할지 결정
      # create-drop: 실행 시점에 엔티티 기준으로 테이블을 생성하고, 종료 시점에 모두 삭제합니다. (개발용)
      ddl-auto: create-drop

    # JPA가 생성하고 실행하는 SQL 쿼리를 개발자가 볼 수 있도록 하는 설정
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true # SQL 쿼리를 보기 좋게 줄바꿈하여 포맷팅
    show-sql: false # 실행되는 SQL 쿼리를 콘솔에 출력

    # 영속성 컨텍스트 범위
    open-in-view: false

  # 메일 발송(SMTP) 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: choongechobiz@gmail.com # 보내는 메일 계정
    password: merg zhtu edxo zszf # 해당 계정의 16자리 앱 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: 'b2F0aHNlY3JleWtleW9hdGhzZWNyZXlrZXlvYXRoc2VjcmV5a2V5'
  expiration-in-ms: 3600000 # 1??

oauth:
  kakao:
    client-id: 1b3011acfb9ddd1a3f7f2fcb1d22e2c6
    redirect-uri: http://localhost:3000/oauth/kakao/redirect

notification:
  policy:
    # 기본 알림 방식을 LOCAL(인앱 알림)으로 설정합니다.
    default: LOCAL
    # 필요 시, 특정 이벤트에 대해 다른 알림 방식을 지정할 수 있습니다.
    #on-create-group: EMAIL

naver:
  map:
    client-secret: ${CLIENT_SECRET:FAKE_KEY}