spring:
  # ===================================================================
  # 1. 데이터소스(DB) 설정
  # ===================================================================
  datasource:
    # 1-1. H2 설정 url: jdbc:h2:mem:solidtask -> 'solidtask'라는 이름의 메모리 기반 DB를 사용합니다.
    h2-db:
      jdbc-url: jdbc:h2:mem:oath
      username: sa # H2 DB 기본 사용자 이름
      password: # 비밀번호는 없음
      driver-class-name: org.h2.Driver # H2 드라이버 지정

#    # 1-2. MySQL 설정 (local 환경에서 사용하지 않으므로 주석 처리)
#    mysql:
#      jdbc-url: jdbc:mysql://localhost:3306/oath?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
#      username: root
#      password: asd1234
#      driver-class-name: com.mysql.cj.jdbc.Driver

    # 1-3. PostgreSQL 설정
    pg:
      jdbc-url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&ApplicationName=oathServer
      username: postgres.ucvalhtcwaxscdmyjoiz
      password: ${POSTGRES_PW:FAKE_PW}
      driver-class-name: org.postgresql.Driver

      hikari:
        maximum-pool-size: 3
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
  
  # ===================================================================
  # 2. H2 데이터베이스 콘솔 설정
  # ===================================================================
  h2:
    console:
      enabled: true # H2 콘솔 기능 활성화
      path: /h2-console # <http://localhost:8080/h2-console>

  # ===================================================================
  # 3. JPA 및 Hibernate 설정
  # ===================================================================
  jpa:
    # 3-1. 공통 JPA 설정
    open-in-view: false # OSIV 비활성화 (권장)

    # 3-2. H2 전용 JPA 속성 (H2JpaConfig에서 사용)
    h2-props:
      properties:
        hibernate:
          ddl-auto: create-drop
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      show-sql: true

#    # 3-3. MySQL 전용 JPA 속성 (MySqlJpaConfig에서 사용하지 않으므로 주석 처리)
#    mysql-props:
#      hibernate:
#      properties:
#        hibernate:
#          # (중요) 운영 환경에서는 'validate' 또는 'none' 사용
#          ddl-auto: create-drop
#          default_batch_fetch_size: 100
#          format_sql: true # SQL 포맷팅
#          dialect: org.hibernate.dialect.MySQLDialect
#      show-sql: true # SQL 로그 출력 (개발용)

    # 3-4. PostgreSQL 전용 JPA 속성 (PgJpaConfig에서 사용)
    pg-props:
      properties:
        hibernate:
          ddl-auto: update
          default_batch_fetch_size: 100
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: oath
      show-sql: true
  
  # 메일 발송(SMTP) 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: choongechobiz@gmail.com # 보내는 메일 계정
    password: merg zhtu edxo zszf # 해당 계정의 16자리 앱 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# 애플리케이션 관련 전역 설정
app:
  base-url: http://localhost:8080

# 이미지 저장 시 파일 저장 위치
upload:
  root-dir: ./uploads/
  chat-dir: chat-images/
  chat-file-dir: chat-file/
  profile-dir: profile/

jwt:
  secret: 'b2F0aHNlY3JleWtleW9hdGhzZWNyZXlrZXlvYXRoc2VjcmV5a2V5'
  expiration-in-ms: 3600000 # 1??

oauth:
  # 카카오
  kakao:
    # A루트
    #client-id: 1b3011acfb9ddd1a3f7f2fcb1d22e2c6
    #redirect-uri: kakao9c1ddd56216285f8f6a6e015073981bd://oauth
    # B 루트
    client-id: 265575d5bd1ece8a9da3afcdc8cd21b8
    redirect-uri: kakao8afa85c4f0d93c3f4b173e745a4e67c9://oauth
  # 페이스북
  facebook:
    client-id: 689815444162329
    client-secret: 91300c17719891f842dabc2d15acae66
    redirect-uri: http://localhost:3000/oauth/facebook/redirect


notification:
  policy:
    # 기본 알림 방식을 COMPOSITE(WebSocket + DB저장)으로 설정
    default: COMPOSITE
    # 특정 이벤트별로 다른 방식 지정 가능
    on-signup: EMAIL
    # on-arrival: WEBSOCKET
    # on-departure: COMPOSITE
    # on-late: EMAIL

map:
  google:
    matrix-endpoint: "https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix"
    api-key: ${GOOGLE_MAP_API_KEY:FAKE_MAP_KEY}
    # 아래는 무슨 값을 응답받을 건지 선택하는 옵션(고정값)
    field-mask: "originIndex,destinationIndex,duration,distanceMeters,status,condition"
  naver:
    geocoding-endpoint: "https://maps.apigw.ntruss.com/map-geocode/v2/geocode?query="
    reverse-geocoding-endpoint: "https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc?coords="
    client-secret: ${CLIENT_SECRET:FAKE_KEY}

ai:
  gemini:
    embedding-endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent"
    embedding-model: "models/gemini-embedding-001"
    api-key: ${GEMINI_API_KEY:FAKE_AI_KEY}
  server:
    url: "http://192.168.0.3:8001/metrics/analyze"
    summary-url: "http://192.168.0.3:8001/metrics/report/{planId}"
    summary-fetch-delay-ms: 5000 # 5초
